### ISSUE TITLE
Gatling-rest unable to complete 'Run reports' on large sets

### ISSUE THREAD

**Issue by marcin-je** [Abiy/distGatling#3]
When running perf tests with 2M+ requests, gatling-rest fails to merge reports from multiple workers. Works fine on smaller sets

**Comment by Abiy** [comment]
Can you provide me with some more information so that i can reproduce the issue: 
- your cluster setup(# of hosts, workers and hosts workers per host etc)
- stack trace will  also be useful
- is it failing when downloading the reports from remote workers or when running generating reports , is it timing out? in that case we can increase the time out.

**Comment by Abiy** [comment]
If it is a timeout you can increase the value to something very high and try it again, right now it is set for 180 seconds.
ServerRepository=>generateReport()
 Object result = sendToMaster(new Master.Report(trackingId, taskEvent), 180);

**Comment by Abiy** [comment]
Did you figure out the issue and a corrective action yet?

**Comment by marcin-je** [comment]
Hi Abiy,
Thanks for response - yes, it was timing out. It can time out either in LB (if you have one in from of gatling-rest) or as you pointed out in the app. Thanks a lot! It would be nice to have that being pulled by front-end instead of relying on long running connections - but that's a minor thing :)
